### ISSUE TITLE
Tests don't appear to work from root of gem checkout

### ISSUE THREAD

**Issue by shcheklein** [fiksu/partitioned#69]
Documentation is insufficient to run tests on partitioned using the checkout. 

Platform is ```ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]```

## Error 1:
```$ rspec spec
/Users/ivan/Projects/partitioned/spec/dummy/config/application.rb:7:in `<top (required)>': uninitialized constant Bundler (NameError)
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ivan/Projects/partitioned/spec/dummy/config/environment.rb:2:in `<top (required)>'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ivan/Projects/partitioned/spec/spec_helper.rb:3:in `<top (required)>'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ivan/Projects/partitioned/spec/monkey_patch_postgres_spec.rb:1:in `<top (required)>'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /Users/ivan/.rbenv/versions/2.3.0/bin/rspec:23:in `load'
	from /Users/ivan/.rbenv/versions/2.3.0/bin/rspec:23:in `<main>'```


## Error 2:
```$ bundle exec rspec spec
/Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'partitioned'. (Bundler::GemRequireError)
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/ivan/Projects/partitioned/spec/dummy/config/application.rb:7:in `<top (required)>'
	from /Users/ivan/Projects/partitioned/spec/dummy/config/environment.rb:2:in `require'
	from /Users/ivan/Projects/partitioned/spec/dummy/config/environment.rb:2:in `<top (required)>'
	from /Users/ivan/Projects/partitioned/spec/spec_helper.rb:3:in `require'
	from /Users/ivan/Projects/partitioned/spec/spec_helper.rb:3:in `<top (required)>'
	from /Users/ivan/Projects/partitioned/spec/monkey_patch_postgres_spec.rb:1:in `require'
	from /Users/ivan/Projects/partitioned/spec/monkey_patch_postgres_spec.rb:1:in `<top (required)>'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/ivan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /Users/ivan/.rbenv/versions/2.3.0/bin/rspec:23:in `load'
	from /Users/ivan/.rbenv/versions/2.3.0/bin/rspec:23:in `<main>'```

**Comment by mada41** [comment]
hi @shcheklein , how you fix the error btw? i got same error :(

**Comment by rands0n** [comment]
Still we don't have any docs about how we run tests with partition! Does anyone here can do it?
